export default () => {
    process.env.API_URL = "http://api.chs.local";
    process.env.APP_NAME = "accounts-filing-web";
    process.env.CACHE_SERVER = "cache_server";
    process.env.CDN_HOST = "http://chs.local";
    process.env.CHS_API_KEY = "CHS_API_KEY";
    process.env.CHS_INTERNAL_API_KEY = "CHS_INTERNAL_API_KEY";
    process.env.CHS_URL = "http://chs.local";
    process.env.COOKIE_DOMAIN = "cookie_domain";
    process.env.COOKIE_NAME = "cookie_name";
    process.env.COOKIE_SECRET = "123456789012345678901234";
    process.env.CIC_FEE = "15";
    process.env.FEEDBACK_LINK = "http://chs.local/feedback";
    process.env.INTERNAL_API_URL = "http://api.chs.local";
    process.env.NUNJUCKS_LOADER_WATCH = "false";
    process.env.OVERSEAS_FEE = "33";
    process.env.SUBMIT_VALIDATION_URL = "http://chs.locl/xbrl_validate/submit";
    process.env.CIC_DISABLE_RADIO = "false";
};
